tools:
  external_code_coverage: true

checks:
  php: true

build:
  environment:
    php:
      version: 7.4.19
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
      project_setup:
        override:
          - 'true'
    tests: true

filter:
  excluded_paths:
    - 'tests/*'

coding_style:
  php: {}
