language: php

php:
  - 7.1
  - 7.2
  - 7.3
  # - nightly

matrix:
  fast_finish: true
  # allow_failures:
  #   - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - composer config -g github-oauth.github.com $GITHUB_TOKEN

install:
  - sudo apt-get install parallel -y
  - travis_retry composer install --no-interaction --prefer-dist --dev

before_script:
  - '/usr/bin/parallel php -l ::: $(/usr/bin/find ./src -iname "*.php")'

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
