name: Unit Tests
on: push
jobs:
  phpunit:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, simplexml, xdebug
        coverage: xdebug
    - name: Download scrutinizer ocular
      run: wget -q -O ocular.phar https://scrutinizer-ci.com/ocular.phar
    - name: Check PHP Version
      run: php --version
    - name: Check Composer Version
      run: composer --version
    - name: Composer Dependencies
      run: composer install --no-interaction --no-suggest --no-progress --prefer-dist --optimize-autoloader
    - name: Lint PHP Files
      run: vendor/bin/parallel-lint src config resources/database web
    - name: Run Testsuite
      run: vendor/bin/phpunit -c phpunit.xml.dist
    - name: Upload code coverage to scrutinizer
      run: php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
    # - name: Upload to CodeCov
    #   uses: codecov/codecov-action@v1.0.3
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     file: ./build/logs/clover.xml
